defaults:
  - model: llava-1.5-7b
  - optim: adamw
  - data: grand
  - loss: alignment
  - trainer
  - dataloader
  - _self_

seed: 42
checkpoint_every_n_epochs: 10

wandb:
  project: saliency-alignment
  entity: teilers-eth-z-rich
