defaults:
  - model: llava-1.5-7b
  - optim: adamw
  - data: png
  - loss: alignment
  - trainer
  - dataloader
  - _self_

seed: 42

checkpoint_dir: models
run_id: ${oc.env:SLURM_JOB_NAME}_${oc.env:MODEL}_${oc.env:CRITERION}_w${oc.env:LAMBDA}_${oc.env:SLURM_JOB_ID}

wandb:
  project: saliency-alignment
  entity: teilers-eth-z-rich
  name: ${run_id}

hydra:
  run:
    dir: outputs/${run_id}
  sweep:
    dir: outputs/${run_id}