# @package dataloader
num_workers: 4
batch_size: 1                       # 4 should work too
persistent_workers: true            # keeps workers alive across iterations
prefetch_factor: 4                  # tune with your I/O
pin_memory: true                    # recommended for GPU training

drop_last: true                    # drop last incomplete batch