# @package dataloader
num_workers: 2
batch_size: 16                      # 4 should work too
persistent_workers: false           # keeps workers alive across iterations
prefetch_factor: 2                  # tune with your I/O
pin_memory: true                    # recommended for GPU training

drop_last: true                     # drop last incomplete batch