# @package trainer
max_epochs: 10
deterministic: true
accelerator: auto
gradient_clip_val: 1.0
enable_model_summary: false

# strategy: ddp
# strategy: deepspeed_stage_3
# devices: 4
# precision: bf16-mixed
# accumulate_grad_batches: 1